pull_request_rules:
  - name: backport patches to cryostat-v2.2 branch
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          - cryostat-v2.2
        assignees:
          - "{{ author }}"

  - name: auto label PRs from reviewers or Dependabot
    conditions:
      - or:
        - author=@reviewers
        - author=dependabot
        - author=app/dependabot
    actions:
      label:
        add:
          - safe-to-test

  - name: dismiss stale reviews
    conditions:
      - base=main
    actions:
      dismiss_reviews:
        approved: [ 'mergify', 'Mergifyio' ]
        changes_requested: [ 'mergify', 'Mergifyio' ]

  - name: block pull requests that manually update web-client submodule
    conditions:
      - or:
        - files=web-client
        - files~=web-client/
    actions:
      review:
        type: REQUEST_CHANGES
        message: >-
            Pull Request blocked. `web-client` submodule updates are performed automatically by CI when that repository
            is updated. Please revert or drop all changes to the `web-client` submodule from this PR and perform any
            required frontend work by opening and merging a PR against
            [cryostat-web](https://github.com/cryostatio/cryostat-web).
