pull_request_rules:
  - name: backport patches to cryostat-v2.1 branch
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          - cryostat-v2.1
        assignees:
          - "{{ author }}"
