---
services:
  cryostat:
    environment:
      - GRAFANA_DATASOURCE_URL=http://jfr-datasource:8080
  jfr-datasource:
    image: ${DATASOURCE_IMAGE-quay.io/cryostat/jfr-datasource:latest}
    container_name: jfr-datasource
    expose:
      - "8080"
