name: 🐞 Bug report
description: File a report to help us improve Cryostat.
title: '[Bug] <title>'
labels: [bug, needs-triage]

body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
      placeholder: Tell us what you expected to see!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        Examples:
          - **OS**: Ubuntu 20.04
          - **Environment**: OpenShift 4.11
          - **Version**: Cryostat 2.3.0
      value: |
          - OS: 
          - Environment: 
          - Version: 
      render: Markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Screenshots? Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
