FROM registry.access.redhat.com/ubi8/openjdk-11:1.3-6

ENV CONF_DIR=/opt/containerjfr.d \
    SSL_TRUSTSTORE=/opt/containerjfr.d/truststore.p12 \
    SSL_TRUSTSTORE_PASS_FILE=/opt/containerjfr.d/truststore.pass

RUN mkdir -p /opt/containerjfr.d

COPY include/truststore-setup.sh /usr/local/bin

RUN sh /usr/local/bin/truststore-setup.sh
