name: build cryostat image

on:
  workflow_call:
    inputs:
      checkout-repo:
        required: false
        type: string
      checkout-ref:
        required: false
        type: string
      build-arch:
        required: true
        type: string
    outputs:
      image-version:
        description: the Cryostat application version that will be built
        value: ${{ jobs.get-pom-properties.outputs.image-version }}

permissions:
  contents: read
  packages: read

jobs:
  get-pom-properties:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.checkout-repo }}
        ref: ${{ inputs.checkout-ref }}
    - id: query-pom
      name: Get properties from POM
      # Query POM for image version and save as output parameter
      run: |
        IMAGE_VERSION="$(mvn validate help:evaluate -Dexpression=cryostat.imageVersionLower -q -DforceStdout)"
        echo "image-version=$IMAGE_VERSION" >> "$GITHUB_OUTPUT"
    outputs:
      image-version: ${{ steps.query-pom.outputs.image-version }}

  build-image:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: [get-pom-properties]
    steps:
    - name: Install qemu
      if: ${{ inputs.build-arch != 'amd64' }}
      continue-on-error: true
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.checkout-repo }}
        ref: ${{ inputs.checkout-ref }}
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: maven-settings
      uses: s4u/maven-settings-action@v2
      with:
        githubServer: false
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore
    - run: git submodule init
    - run: git submodule update
    - run: mvn -B -U -Dbuild.arch=${{ inputs.build-arch }} clean package
      env:
        GITHUB_TOKEN_REF: ${{ secrets.GITHUB_TOKEN }}
    - name: Save cryostat image
      run: podman save -o cryostat-${{ inputs.build-arch }}.tar --format oci-archive quay.io/cryostat/cryostat
    - uses: actions/upload-artifact@v3
      with:
        name: cryostat-${{ inputs.build-arch }}
        path: /home/runner/work/cryostat/cryostat/cryostat-${{ inputs.build-arch }}.tar
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: save
